### ISSUE TITLE
ValueError: Receive unexpected status code 504 from the API.

### ISSUE THREAD

**Issue by Jimchoo91** [Unstructured-IO/unstructured-api#255] opened 2023-09-26 20:27 UTC
As in the subject line, I have received this error a few times across the course of the last few hours.

Full code
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-370-f9d5eba144d9> in <module>
      9 )
     10 
---> 11 chev_docs_1 = loader.load()

/opt/anaconda3/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py in load(self)
     84     def load(self) -> List[Document]:
     85         """Load file."""
---> 86         elements = self._get_elements()
     87         if self.mode == "elements":
     88             docs: List[Document] = list()

/opt/anaconda3/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py in _get_elements(self)
    267 
    268     def _get_elements(self) -> List:
--> 269         return get_elements_from_api(
    270             file_path=self.file_path,
    271             api_key=self.api_key,

/opt/anaconda3/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py in get_elements_from_api(file_path, file, api_url, api_key, **unstructured_kwargs)
    202         from unstructured.partition.api import partition_via_api
    203 
--> 204         return partition_via_api(
    205             filename=file_path,
    206             file=file,

/opt/anaconda3/lib/python3.8/site-packages/unstructured/partition/api.py in partition_via_api(filename, content_type, file, file_filename, api_url, api_key, **request_kwargs)
     88         files = [
     89             ("files", (metadata_filename, file, content_type)),  # type: ignore
---> 90         ]
     91         response = requests.post(
     92             api_url,

ValueError: Receive unexpected status code 504 from the API.
```

**Comment by awalker4** [comment] 2023-10-09 22:05
Sorry for the delay on this. The error happens with the pdf you posted [here](https://github.com/Unstructured-IO/unstructured-api/issues/220), correct? I just reproduced a 504 error with this and will do some digging.

**Comment by awalker4** [comment] 2023-10-09 22:11
I think this is due to pdfs taking a long time to process, and sometimes the server times out. As a workaround, you may want to try sending individual pages and combining the results. Here's a gist of splitting up a pdf and sending the pages to the api. In Langchain's case, I _think_ you can write out the pages and pass individual filenames into the loader.

**Comment by awalker4** [comment] 2023-10-26 17:15
We just addressed some low memory issues in the hosted API which could lead to 502s. And the comment above should hopefully remove any 504 timeouts. Going to close this, but please let us know if the issue persists.

**Closed by awalker4** 2023-10-26 17:15 UTC
